/// This code was generated by DTNet Scaffolder.
// template: ViewModel.IRepositoryWrapper.cs
// class: Role
namespace BlueOnion.ViewModel.Interfaces
{
    public interface IRepositoriesWrapper : INonAGRepositoriesWrapper
    {
			
    }
}